import os
import sys
import base64
import requests
from datetime import datetime

sys.stdout.reconfigure(encoding='utf-8')

ADO_PAT = os.environ.get("ADO_PAT")
ADO_ORG = os.environ.get("ADO_ORG", "karmadhipatishanidev")
ADO_PROJECT = os.environ.get("ADO_PROJECT", "JaiShanidev")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GEMINI_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}"


def ado_headers():
    token = base64.b64encode(f":{ADO_PAT}".encode()).decode()
    return {
        "Authorization": f"Basic {token}",
        "Content-Type": "application/json"
    }


def call_gemini(prompt):
    response = requests.post(GEMINI_URL, json={
        "contents": [{"parts": [{"text": prompt}]}]
    })
    data = response.json()
    if response.ok:
        return data["candidates"][0]["content"]["parts"][0]["text"]
    return f"Gemini unavailable: {response.status_code}"


def fetch_backlog():
    print("Fetching open work items from ADO Boards...")
    url = f"https://dev.azure.com/{ADO_ORG}/{ADO_PROJECT}/_apis/wit/wiql?api-version=7.0"
    query = {
        "query": """
            SELECT [System.Id], [System.Title], [System.WorkItemType],
                   [System.State], [Microsoft.VSTS.Common.Priority]
            FROM WorkItems
            WHERE [System.TeamProject] = @project
            AND [System.State] <> 'Closed'
            AND [System.State] <> 'Resolved'
            ORDER BY [Microsoft.VSTS.Common.Priority] ASC,
                     [System.CreatedDate] DESC
        """
    }
    response = requests.post(url, json=query, headers=ado_headers())
    if not response.ok:
        print(f"Failed to fetch backlog: {response.status_code} - {response.text}")
        return []

    work_item_refs = response.json().get("workItems", [])
    if not work_item_refs:
        print("No open work items found")
        return []

    print(f"Found {len(work_item_refs)} open work items")
    ids = [str(item["id"]) for item in work_item_refs[:20]]
    return fetch_work_item_details(ids)


def fetch_work_item_details(ids):
    fields = "System.Id,System.Title,System.WorkItemType,System.State,Microsoft.VSTS.Common.Priority,System.Tags"
    url = f"https://dev.azure.com/{ADO_ORG}/{ADO_PROJECT}/_apis/wit/workitems?ids={','.join(ids)}&fields={fields}&api-version=7.0"
    response = requests.get(url, headers=ado_headers())
    if not response.ok:
        print(f"Failed to fetch details: {response.status_code}")
        return []
    return response.json().get("value", [])


def generate_sprint_plan(work_items):
    print("Generating sprint plan with Gemini...")
    items_text = ""
    for item in work_items:
        fields = item.get("fields", {})
        items_text += f"- [{fields.get('System.WorkItemType')}] #{item['id']}: {fields.get('System.Title')} (Priority: {fields.get('Microsoft.VSTS.Common.Priority', 'N/A')}, Tags: {fields.get('System.Tags', 'none')})\n"

    prompt = f"""You are an agile sprint planning assistant.
Below is the current backlog of open work items for project {ADO_PROJECT}.

Backlog:
{items_text}

Please provide a sprint plan with:
1. **Recommended Sprint Items** - top 5 items to include in next sprint with brief reason
2. **Priority Bugs** - any bugs that need immediate attention
3. **Technical Debt** - any items tagged as tech debt or improvements
4. **Suggested Sprint Goal** - one sentence sprint goal

Keep the response concise and actionable."""

    return call_gemini(prompt)


def get_wiki_id():
    print("Fetching wiki ID...")
    url = f"https://dev.azure.com/{ADO_ORG}/{ADO_PROJECT}/_apis/wiki/wikis?api-version=7.0"
    response = requests.get(url, headers=ado_headers())
    print(f"Wikis response: {response.status_code}")
    if not response.ok:
        print(f"Failed to fetch wikis: {response.text[:200]}")
        return None
    wikis = response.json().get("value", [])
    if not wikis:
        print("No wikis found")
        return None
    wiki_id = wikis[0]["id"]
    wiki_name = wikis[0]["name"]
    print(f"Using wiki: {wiki_name} (ID: {wiki_id})")
    return wiki_id


def post_sprint_plan_as_wiki(sprint_plan):
    print("Posting sprint plan as ADO wiki page...")
    date_str = datetime.now().strftime("%Y-%m-%d")

    wiki_id = get_wiki_id()
    if not wiki_id:
        print("No wiki found - printing plan to console")
        print("\n" + "="*50)
        print(sprint_plan)
        print("="*50 + "\n")
        return False

    page_content = f"""# Sprint Plan — {date_str}

> Auto-generated by JaiShanidev Sprint Planning Agent

{sprint_plan}

---
*Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")} UTC*
*Agent: Gemini 2.5 Flash | Source: ADO Boards backlog*"""

    url = f"https://dev.azure.com/{ADO_ORG}/{ADO_PROJECT}/_apis/wiki/wikis/{wiki_id}/pages?path=/Sprint-Plans/{date_str}&api-version=7.0"
    print(f"Posting to: {url}")

    headers = ado_headers()
    headers["Content-Type"] = "application/json"

    response = requests.put(url, json={"content": page_content}, headers=headers)
    print(f"Wiki post response: {response.status_code}")

    if response.ok:
        print(f"Sprint plan posted to wiki: /Sprint-Plans/{date_str}")
        return True
    else:
        print(f"Wiki post failed ({response.status_code}): {response.text[:300]}")
        print("\n" + "="*50)
        print(sprint_plan)
        print("="*50 + "\n")
        return False


def main():
    print("Sprint Planning Agent starting...")
    print(f"ADO Org: {ADO_ORG}, Project: {ADO_PROJECT}")

    if not ADO_PAT:
        print("ADO_PAT not set - skipping sprint planning")
        sys.exit(0)

    work_items = fetch_backlog()
    if not work_items:
        print("No work items to plan - exiting")
        sys.exit(0)

    sprint_plan = generate_sprint_plan(work_items)
    post_sprint_plan_as_wiki(sprint_plan)
    print("Sprint Planning Agent complete!")


if __name__ == "__main__":
    main()